config/routes.rb
Rails.application.routes.draw do
  get 'about-us', to:"about#index", as: :about
  get 'community', to:'community#index', as: :community
  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController 
  def index 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/community_controller.rb
class CommunityController < ApplicationController 
  def index 
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController 
  def index 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/community/index.html.erb
<h1>Community Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render partial:"shared/navbar" %>
  <div class='container'>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to Scheduled Tweets</h1>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Navbar</a>
    </div>
    <ul class="nav">
      <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Community", community_path, class:"nav-link"  %>
      </li>
    </ul>
  </div>
</nav>